language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t bhavesh2781993/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bhavesh2781993/docker-react npm run test
